[package]
name = "enum_like_derive"
version = "0.1.0"
authors = ["Badel2 <2badel2@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "0.4"

[dependencies.syn]
version = "0.12"
features = ["extra-traits"]
