[package]
name = "example"
version = "0.1.0"
authors = ["Badel2 <2badel2@gmail.com>"]

[dependencies]
enum-like = { path = "../enum-like" }
enum-like-derive = { path = "../enum-like-derive" }
enum-vec = { path = "../enum-vec" }
